### ISSUE TITLE
White waterfall & latest firmware update reverted to v1.1-17

### ISSUE THREAD

**Issue by adamsj182** [erikkaashoek/tinySA#10]
After building from source and updating firmware released Sept. 28, the white waterfall that came from the vendor was not fixed. Also, firmware reflects v1.1-17 whereas firmware located at "http://athome.kaashoek.com/tinySA/DFU/" reflects v1.1-21.

This photo reflects the firmware version after update:
![123874479_683065565675294_484305038061075529_n](https://user-images.githubusercontent.com/50853374/98435070-7ed1f300-2090-11eb-9ff4-b38abe66deb5.jpg)

And this photo reflects the same white waterfall that I got from the vendor but after the update:
![124071179_995418514269612_6082062189881815659_n](https://user-images.githubusercontent.com/50853374/98435513-a32dcf80-2090-11eb-85b9-0e2a3450f1e6.jpg)

Not sure why the v1.1-17 did not fix the white waterfall but I'll try updating firmware to v1.1-21 and see if that fixes it. Not sure if I'll need to completely wipe the old firmware or what???

**Comment by erikkaashoek** [comment]
Solved
