### ISSUE TITLE
TinySA Hung Up

### ISSUE THREAD

**Issue by VAskyfly** [erikkaashoek/tinySA#13]
Power TinySA on and press round knob, main menu comes up and I select config, then get no info screen, press round knob or tap screen and get REFER DELTA NOISE TRACKING, etc info screen. I can select delete or back and get no info screen. Keep hanging in that loop.

**Comment by AdilCtn** [comment]
Tekrar Güncelleyin, beyaz ekran sorunu bölümünde göçen flaş bölümünde de bu yazımı paylaşmıştım fakat flaş firmware yazılımını tekrar silerek yükeme yapınız, aşağıda belirtmiş olduğum farklı flaş günceleme update programı ile yapınız,
Selam arkadaşı, üzülmeyinin her şeyi ben de> ve içeriden, 1-->Öncelikle windows üzerinde bu programlayıcıyı PTM32CubeProgrammer (STM32CubeProgrammer).
2->>>> orjinal son Fimware güncellemesinin (.bin) uzantılı olan güncelleme fimwaresini indirilen ve İndirilen tinySA.bin olarak yeniden adlandırın.
3--> beyaz ekran ile karşılaşılacaklar:) Üzülmeyi uygulayınız.
Kapatmak.
Arkadaki vidayı çıkararak kasayı 4
VDD ve BOOT0 olarak işaretlenmiş iki pcb ucu bir kablodan ile malzemeden
az sayıda TinySa yı Açın.
PC ile USB Bağlantısını yapın.
LCD beyaza döner veya zaten beyaz olmuşsa da aynı şey, bu yakın flaşlama süreci olmakta olduğunu unutmayın.
(STM32'den USB'ye göre, (STM32) USB Bağlantısını görecek ve yapmanız gereken ilk şey i ve Proğramın Bağlan, olarak da tıklayın altta Silgi işareti var oradam eski boya ikinci şey verilerini ve altta siyah işaret ile eski yükleme verilerini verilerini da silim , hatta proğramı tekrar tekrar açalım TinySA ile tekrardan kurulumunu USB tekrar bağlantı bağlantısıyla tekrar yapın.
Şimdi gelelim son adım için Programlama Yazımdaki OPEN ye tıklayın, indirdiğimiz ve adından kısalttığımız TinySa.bin hedefimiz ve Pro üst tarafta DOWNLOAD Butonu belirecek, butonu belirecek ve saniyeler içinde yeni yazılacak olacak. VDD ve BOOT0 Bağlantısını kesin, TinySA'nızın ilgili olduğu ve 4 vidasını tekrar vidalayın. Daha sonra D Modu ile aynı yazılım yükleme sonrası güncellemeye devam edebilirsiniz. göçmüş ve beyaz ekran bu uzun anlatımda olduğu gibi DFU Modo olarak kablo ile şönt yapılmakta.
GEÇMİŞ OLSUN GÜLE GÜLE TinySA'yı başlayabilirsiniz, hem daha hızlı hem de daha güvenli bir Flaşlama da bu yolla öğrenmiş oldunuz. Antalya/Türkiye Amatör Telsiz Lisans Kodum TA4DIL

**Comment by erikkaashoek** [comment]
Please ask general support questions here: https://groups.io/g/tinysa/messages
