### ISSUE TITLE
PC Software - glscopeclient considered?

### ISSUE THREAD

**Issue by xtc0r** [erikkaashoek/tinySA#47]
Hi,
just wondering if you could use glscopeclient for the TinySA. I stumbeled over the SW when looking for a opensource oscilloscope. 
The SW seems to be useable for different HW.

https://github.com/glscopeclient/scopehal-apps

Developer: [@azonenberg](https://github.com/azonenberg)

He also has some youtube videos demonstrating the SW [here](https://www.youtube.com/playlist?list=PLBNA3N3RCc8ovjLr9XG8wT7gBLL1q41-s)

And in discord I spotted him in the Thunderscope (open source oscilloscope) [discord server](https://discord.gg/mCUsZ5BQ)

**Comment by erikkaashoek** [comment]
Looks good, but att he moment I have too many projects already so the PC App has lower priority
