### ISSUE TITLE
TinySA PC App does not display correct frequency markers

### ISSUE THREAD

**Issue by BernieMurphy** [erikkaashoek/tinySA#6]
I have attached a screen shot showing the issue.

![TinySA_Screenshot 2020-09-14 22 07 41](https://user-images.githubusercontent.com/69081532/93229213-57237600-f744-11ea-8fff-64807d78d442.png)

**Comment by erikkaashoek** [comment]
Not sure what you mean with "not correct".
- Not the same as set in the tinySA?
- The frequency of the markers displayed is wrong?

**Comment by BernieMurphy** [comment]
Erik

Please review the picture I have included on the GitHub trouble ticket.  

The problem is clearly visible as any marker beyond the first marker,  the marker level in dBm is not correct.

Sorry I did not describe the problem more precisely. The problem always seems to be with the second markers and beyond. The first marker always has the correct value in dBm.

Thank you,

Bernie

Bernie

Sent from my iPad 7th generation
(most typos in this message have been introduced by highly sophisticated auto-correction software)

**Comment by erikkaashoek** [comment]
You are displaying delta markers. You can disable this in the menu

**Comment by BernieMurphy** [comment]
Thanks Erik.  

I assume the delta value is computed relative to the first marker?  A tiny delta character in front of the marker reading would be a really  cool feature request  (when in delta mode). Perhaps a new FAQ entry to prevent you from having to answer this question again?

Would you like me to open a formal feature request on GitHub for tracking purposes?

This tinySA product continues to amaze me.

Thank you, again.

73, Bernie, VE3FWF

Sent from my iPad 7th generation
(most typos in this message have been introduced by highly sophisticated auto-correction software)

**Comment by erikkaashoek** [comment]
The level is indicated as dBc to signal delta
TinySA.exe will stop
TinySA-app will be the future

**Comment by BernieMurphy** [comment]
Thank you Erik.  Excellent
