### ISSUE TITLE
Crash Dump while tapping "outside options" /not active area 

### ISSUE THREAD

**Issue by fpaolo63** [erikkaashoek/tinySA#9]
in "MODE" setup, tapping outside options (see yellow circle) I got a crash dump
100% repro
SW: tinySA_v1.0-62

![2020-11-07 01 16 00aa](https://user-images.githubusercontent.com/19231730/98425966-65807500-2097-11eb-995c-8bd20e0aa361.jpg)
 

![2020-11-06 21 44 08](https://user-images.githubusercontent.com/19231730/98425253-c3f82400-2094-11eb-8827-0aace99859bd.jpg)

**Comment by erikkaashoek** [comment]
Solved
